// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhj-4uOWuhgVVPweUSa1QNzT7YsZCpXEs',
    appId: '1:97205150526:web:d1b097c6257cba3c60c26f',
    messagingSenderId: '97205150526',
    projectId: 'user-account-8d90f',
    authDomain: 'user-account-8d90f.firebaseapp.com',
    storageBucket: 'user-account-8d90f.appspot.com',
    measurementId: 'G-H9JLHYVE7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxN9l5zQ-aSGXMQfhDjp2wHJc4JtQHWB8',
    appId: '1:97205150526:android:77c8e087c8d02d3960c26f',
    messagingSenderId: '97205150526',
    projectId: 'user-account-8d90f',
    storageBucket: 'user-account-8d90f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqqgSntcx76WHZfhQg1seroXtzheiEI0',
    appId: '1:97205150526:ios:1cba8ed6620aed5d60c26f',
    messagingSenderId: '97205150526',
    projectId: 'user-account-8d90f',
    storageBucket: 'user-account-8d90f.appspot.com',
    iosBundleId: 'com.example.userAccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHqqgSntcx76WHZfhQg1seroXtzheiEI0',
    appId: '1:97205150526:ios:3aed6091516d970160c26f',
    messagingSenderId: '97205150526',
    projectId: 'user-account-8d90f',
    storageBucket: 'user-account-8d90f.appspot.com',
    iosBundleId: 'com.example.userAccount.RunnerTests',
  );
}
